### ISSUE TITLE
Tutorial links issue

### ISSUE THREAD

**Issue by cristeigabriela** [haxpor/sdl2-manpage#8]
Hello! First, thank you very much for this. This convenience helps me a lot during development.

It appears that every page that contains the following format:

```
wiki.libsdl.org/Tutorials/{}
```

is actually wrong, and that it should be

```
wiki.libsdl.org/Tutorials-{}
```

Example being in SDL_AudioStream(3).

**Comment by cristeigabriela** [comment]
I've created a pull request (#9) to address this issue. If interested, I've used this:

```
grep -rl 'Tutorials/' ./ | xargs sed -i 's/Tutorials\//Tutorials-/g'
```

to address the issue.

**Comment by haxpor** [comment]
Acknowledged, and thanks. Merged!
